### ISSUE TITLE
不推荐使用bilibili-api

### ISSUE THREAD

**Issue by XzaiCloud** [OverSky-gtq/AI-Vup#4]
这是一个过时的库，很多功能无法使用

**Comment by OverSky-gtq** [comment]
好的，但监听弹幕还是能用的。另外这个项目只是我存起来自用，不用一直盯着给建议。

**Comment by XzaiCloud** [comment]
![9TD(A0ZR5861IR1UGHFF{2I](https://user-images.githubusercontent.com/98635300/226317465-0486f1b2-1bda-4489-8c8a-da596e5a6d1f.jpg)

**Comment by XzaiCloud** [comment]
推荐使用bilibili-api-python

**Comment by OverSky-gtq** [comment]
6
